### ISSUE TITLE
String data, right truncated: 1406 Data too long for column log_error and log 

### ISSUE THREAD

**Issue by ofirgalcon** [munkireport/munkireportinfo#11]
`String data, right truncated: 1406 Data too long for column log_error at row 1 (SQL: update munkireportinfo`

and

`String data, right truncated: 1406 Data too long for column log at row 1 (SQL: update munkireportinfo`

I tried changing the data type to MediumText but that didn't help

**Comment by tuxudo** [comment]
This is caused by a runaway MunkiReport log on the client. Once that is resolved, this error will be resolved. Uploading and storing more than the 64KB of the `text` column is not a good idea.
